 saved_path: sql
 databases:
   seinfeld:
     name:        Seinfeld
     description: A database about nothing.
     url_path:    seinfeld
     saved_path:  seinfeld
     db_database: seinfeld
     db_username: root
     db_password: root
     db_port:     3306
     db_host:     db
