 saved_path: sql
 databases:
   seinfeld:
     name:        Seinfeld
     description: A database about nothing.
     url_path:    seinfeld
     saved_path:  seinfeld
     db_database: seinfeld
     db_username: newman
     db_password: drakescoffeecake
     db_port:     <%= Integer(ENV.fetch('DB_PORT')) %>
     db_host:     <%= ENV.fetch('DB_HOST') %>
