name: Development
port: 8080
environment: development
list_url_path: /sqlui
databases:
  shows:
    display_name: Shows
    description:  Some databases about nothing.
    url_path:     /sqlui/shows
    saved_path:   sql/shows
    tables:
      friends.characters:
        alias: c
        boost: 1
    client_params:
      username: root
      password: root
      port:     3306
      host:     <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  seinfeld:
    display_name: Seinfeld
    description:  A database about nothing.
    url_path:     /sqlui/seinfeld
    saved_path:   sql/seinfeld
    client_params:
      database: seinfeld
      username: newman
      password: drakescoffeecake
      port:     3306
      host:     <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  friends:
    display_name: Friends
    description:  Another database about nothing.
    url_path:     /sqlui/friends
    saved_path:   sql/friends
    columns:
      name:
        links:
          - short_name: G
            long_name:  Google
            template:   https://www.google.com/search?q={*}
          - short_name: W
            long_name:  Wiki
            template:   https://friends.fandom.com/wiki/Special:Search?query={*}
    tables:
      characters:
        alias: c
        boost: 1
      actors:
        alias: a
    joins:
      - label: 'actors to characters'
        apply: 'actors a ON a.id = c.actor_id'
      - label: 'characters to actors'
        apply: 'characters c ON c.actor_id = a.id'
    client_params:
      database: friends
      username: heckles
      password: keepitdown
      port:     3306
      host:     <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
