name: Development
list_path: /sqlui
databases:
  seinfeld:
    display_name: Seinfeld
    description:  A database about nothing.
    url_path:     /sqlui/seinfeld
    saved_path:   sql/seinfeld
    client_params:
      database:     seinfeld
      username:     newman
      password:     drakescoffeecake
      port:         <%= Integer(ENV.fetch('DB_PORT')) %>
      host:         <%= ENV.fetch('DB_HOST') %>
