name: Development
port: 8080
environment: development
list_url_path: /sqlui
databases:
  seinfeld:
    display_name: Seinfeld
    description:  A database about nothing.
    url_path:     /sqlui/seinfeld
    saved_path:   sql/seinfeld
    client_params:
      database:     seinfeld
      username:     newman
      password:     drakescoffeecake
      port:         3306
      host:         <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
