name: Development
port: <%= ENV.fetch('APP_PORT') %>
environment: <%= ENV.fetch('ENV') %>
base_url_path: /sqlui
airbrake:
  server:
    enabled:     <%= ['true', '1'].include?(ENV.fetch('AIRBRAKE_SERVER_ENABLED', 'false')) %>
    project_id:  <%= ENV.fetch('AIRBRAKE_SERVER_PROJECT_ID', '') %>
    project_key: <%= ENV.fetch('AIRBRAKE_SERVER_PROJECT_KEY', '') %>
  client:
    enabled:     <%= ['true', '1'].include?(ENV.fetch('AIRBRAKE_CLIENT_ENABLED', 'false')) %>
    project_id:  <%= ENV.fetch('AIRBRAKE_CLIENT_PROJECT_ID', '') %>
    project_key: <%= ENV.fetch('AIRBRAKE_CLIENT_PROJECT_KEY', '') %>
defaul_saved_config: &default_saved_config
  author:
    name: 'SQLUI'
    email: nicholasdower+sqlui@gmail.com
  token: <%= ENV.fetch('GITHUB_TOKEN', nil) %>
  owner: nicholasdower
  repo: sqlui
  branch: master
databases:
  shows:
    display_name: Shows
    description:  Some databases about nothing.
    url_path:     shows
    columns:
      name:
        links:
          google:
            short_name: G
            long_name:  Google
            template:   https://www.google.com/search?q={*}
          wiki:
            short_name: W
            long_name:  Wiki
            template:   https://friends.fandom.com/wiki/Special:Search?query={*}
    tables:
      friends.characters:
        alias: c
        boost: 1
    client_params:
      username: root
      password: root
      port:     3306
      host:     <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  seinfeld:
    display_name: Seinfeld
    description:  A database about nothing.
    url_path:     seinfeld
    client_params:
      database: seinfeld
      username: newman
      password: drakescoffeecake
      port:     3306
      host:     <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  friends:
    display_name: Friends
    description:  A database about even less.
    url_path:     friends
    <% if ENV.key?('GITHUB_TOKEN')%>
    saved_config:
      <<: *default_saved_config
      regex: ^sql/friends/.*[.]sql$
    <% end %>
    columns:
      name:
        links:
          google:
            short_name: G
            long_name:  Google
            template:   https://www.google.com/search?q={*}
          wiki:
            short_name: W
            long_name:  Wiki
            template:   https://friends.fandom.com/wiki/Special:Search?query={*}
    tables:
      characters:
        alias: c
        boost: 1
      actors:
        alias: a
    joins:
      actors_to_charactors:
        label: 'actors to characters'
        apply: 'actors a ON a.id = c.actor_id'
      charactors_to_actors:
        label: 'characters to actors'
        apply: 'characters c ON c.actor_id = a.id'
    client_params:
      database: friends
      username: heckles
      password: keepitdown
      port:     3306
      host:     <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
