services:
  db:
    container_name: sqlui_db
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ['CMD', 'mysql', '--user=root', '--password=root', '--execute', 'show databases;']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
  rollup:
    container_name: sqlui_rollup
    build: .
    command: bash -c "cd /sqlui && make start-rollup-local"
    volumes:
      - .:/sqlui
  server:
    container_name: sqlui_server
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
    command: bash -c "cd /sqlui && ./scripts/rerun --dir app --dir client/resources --file development_config.yml -- bundle exec ruby ./bin/sqlui development_config.yml"
    volumes:
      - .:/sqlui
    ports:
      - "8080:8080"
    depends_on:
      rollup:
        condition: service_started
      db:
        condition: service_healthy
  hub:
    container_name: sqlui_hub
    image: selenium/hub:latest
    environment:
      GRID_BROWSER_TIMEOUT: 10000 # 10 seconds
      GRID_NEW_SESSION_WAIT_TIMEOUT: 20000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 10000
    ports:
      - "4444:4444"
  node-chrome:
    container_name: sqlui_node_chrome
    image: selenium/node-chrome:latest
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_VNC_NO_PASSWORD: 1
    volumes:
      - /dev/shm:/dev/shm
