services:
  db:
    container_name: sqlui_db
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: development
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    ports:
      - '60330:3306'
    healthcheck:
      test: ['CMD', 'mysql', '--user=developer', '--password=password', '--database=development', '--execute', 'show databases;']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
  db-ready:
    container_name: sqlui_db_ready
    image: docker.localproxy.sc:42042/base:latest-${HOSTARCH}
    command: 'true'
    depends_on:
      db:
        condition: service_healthy
  server:
    container_name: sqlui_server
    build: .
    environment:
      PORT: 8080
      APP_ENV: development
    command: bash -c "cd /sqlui && bundle exec ruby ./bin/sqlui development_config.yml"
    volumes:
      - .:/sqlui
    ports:
      - "8080:8080"
    depends_on:
      - db-ready
