services:
  sqlui_db:
    container_name: sqlui_db
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./sql/my.cnf:/etc/mysql/my.cnf:ro
      - ./logs/mysql-general.log:/var/log/mysql-general.log
      - ./logs/mysql-error.log:/var/log/mysql-error.log
    command: mysqld --general-log --general-log-file=/var/log/mysql-general.log --log-error=/var/log/mysql-error.log
    healthcheck:
      test: ['CMD', 'mysql', '--user=root', '--password=root', '--execute', 'show databases;']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    networks:
      - sqlui
  sqlui_server:
    container_name: sqlui_server
    image: nicholasdower/sqlui:latest
    command: bash -c "cd /sqlui && make start-server-from-docker"
    volumes:
      - .:/sqlui
    ports:
      - "8080:8080"
    depends_on:
      sqlui_db:
        condition: service_healthy
    healthcheck:
      test: curl --silent --fail localhost:8080/-/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 10s
    networks:
      - sqlui
  sqlui_hub:
    container_name: sqlui_hub
    image: selenium/hub:latest
    environment:
      GRID_BROWSER_TIMEOUT: 10000 # 10 seconds
      GRID_NEW_SESSION_WAIT_TIMEOUT: 20000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 10000
    ports:
      - "4444:4444"
    networks:
      - sqlui
  sqlui_node-chrome:
    container_name: sqlui_node_chrome
    image: selenium/node-chrome:latest
    environment:
      SE_EVENT_BUS_HOST: sqlui_hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_VNC_NO_PASSWORD: 1
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - sqlui
networks:
  sqlui:
    name: 'sqlui'
    external: true
