saved_path: sql
databases:
  local_development:
    name:        Local Development
    path:        local_development
    db_database: development
    db_username: root
    db_password: root
    db_host:     127.0.0.1
    description: Local development database
