saved_path: sql
databases:
  development:
    name:        Development
    url_path:    development
    saved_path:  development
    db_database: development
    db_username: root
    db_password: root
    db_host:     127.0.0.1
    description: Local development database
