 saved_path: sql # Path to the directory containing saved SQL files.
 databases:
   development:
     name:        Development # Database display name to be used in the UI.
     description: description # Database display name to be used in the UI.
     url_path:    development # Path to use in the URL to access this database.
     saved_path:  development # Path within the root saved path containing saved SQL files.
     db_database: development # Database name.
     db_username: root        # Database username.
     db_password: root        # Database password.
     db_host:     127.0.0.1   # Database host.
