#!/bin/bash

set -e -u -o pipefail

if [ ! -f client/resources/sqlui.js ] || [ client/sqlui.js -nt client/resources/sqlui.js ]; then
  rm -f client/resources/sqlui.js
  ./node_modules/rollup/dist/bin/rollup --config ./rollup.config.js --bundleConfigAsCjs
  chmod 444 client/resources/sqlui.js
fi
