#!/bin/bash

set -e -u -o pipefail

scripts_dir=$(dirname $0)
root_dir=$(cd $scripts_dir/.. && pwd)

$scripts_dir/create-docker-network

interactive=""
if [ -t 0 ]; then
  interactive="--tty --interactive"
fi
docker run --rm $interactive --network sqlui_default --volume $root_dir:/sqlui --workdir /sqlui $@
