#!/bin/bash

set -e -u -o pipefail

EXPECTED=`cat .nvmrc`
CURRENT=`node -v`

if [ "$EXPECTED" != "$CURRENT" ]; then
  source $HOME/.nvm/nvm.sh;
  nvm use --silent || (echo "failed to set node version to $EXPECTED"; exit 1)
fi
