#!/bin/bash

set -e -u -o pipefail

expected_node=`cat .nvmrc`
current_node=`node -v`

if [ "$expected_node" != "$current_node" ]; then
  . $NVM_DIR/nvm.sh
  echo 'warning: switching to Node '$expected_node', run `nvm use` to avoid this delay'
  nvm use > /dev/null
fi

current_node=`node -v`
if [ "$expected_node" != "$current_node" ]; then
  echo 'Node '$expected_node' required, `nvm use` resulted in '$current_node >&2
  exit 1
fi

$@
