#!/usr/bin/env ruby
# frozen_string_literal: true

require 'find'
require 'optparse'
require 'set'

# Runs the specified command and restarts it when files in the specified directories change.
class Watcher
  MIN_REFRESH_DELAY = 2

  def initialize(includes, excludes, command)
    raise 'missing includes' unless includes&.any?
    raise 'missing command' unless command&.any?


    @includes = includes
    @excludes = excludes
    @command = command
    @watched_files = watched_files
    @alive = true
    @last_change = Time.now
  end

  def watch
    @pid = Process.spawn(*@command, pgroup: true) if @alive
    while @alive
      minutes_since_last_change = ((Time.now - @last_change) / 60).to_i
      minutes_since_last_change = [minutes_since_last_change, 0].max
      delay = [60, 20, 10, 5, 0].find { |t| minutes_since_last_change >= t }
      delay = [delay, MIN_REFRESH_DELAY].max
      sleep delay
      refresh
    end
  end

  def refresh
    files = updated_files
    return if files.empty?

    puts "changed: #{files.join(' ')}"
    @last_change = Time.now
    kill('TERM')
    @pid = Process.spawn(*@command, pgroup: true) if @alive
  end

  def kill(signal)
    return unless @pid

    Process.kill(signal, -Process.getpgid(@pid))
  rescue Errno::ESRCH
    # ignore
  ensure
    @pid = nil
  end

  def die(signal)
    kill(signal)
    @alive = false
  end

  def watched_files
    files = Find.find(*@includes).to_a - Find.find(*@excludes).to_a
    files = files.select { |f| FileTest.file?(f) }
    entries = files.flat_map do |file|
      if FileTest.file?(file)
        [[file, File.mtime(file).to_i]]
      else
        []
      end
    end
    entries.to_set
  end

  def updated_files
    new_watched_files = watched_files
    difference = (new_watched_files - @watched_files) + (@watched_files - new_watched_files)
    @watched_files = new_watched_files
    difference.map(&:first)
  end
end

def help
  warn 'Usage: ./scripts/rerun (--include path... | --exclude path...)... -- <command>'
  exit 1
end

separator = ARGV.find_index('--')
help unless separator&.between?(1, ARGV.size - 2)
path_args = ARGV[0...separator]

paths = {
  '--include' => [],
  '--exclude' => []
}
while path_args.any?
  type = path_args.shift
  if ['--include', '--exclude'].include?(type)
    found = []
    while path_args.any? && !path_args.first.start_with?('--')
      found << path_args.shift
    end
    help if found.empty?
    paths[type] += found
  else
    help
  end
end

command = ARGV[(separator + 1)..]
help if command.empty?

watcher = Watcher.new(paths['--include'], paths['--exclude'], command)

Signal.trap('INT') do
  watcher.die('INT')
  exit 2
end

Signal.trap('TERM') do
  watcher.die('TERM')
  exit 15
end
watcher.watch
