#!/usr/bin/env bash

set -e -u -o pipefail

if [ $# -lt 3 ] || [ $2 != '--' ]; then
  echo "Usage: $0 <env> -- command..." >&2
  exit 1
fi

env="$1"
shift 2
if [ ! -f "./envs/$env" ]; then
  echo "$env not found" >&2
  exit 1
fi

echo "loading $env"
set -a
cd ./envs
eval "$(cat "$env")"
cd ..

$@
