name: Build, Lint & Test

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!**/*.md'
      - '!/todo'
      - '!/.release-notes'
      - '!/scripts/release'
      - '!/scripts/rerun'
      - '!/LICENSE.txt'
      - '!/.github/dependabot.yml'
      - '!/.github/workflows/release.yml'

jobs:
  test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: make install
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Start Database
        run: make start-db-detached
      - name: Start Selenium
        run: make start-selenium-detached
      - name: Test
        run: make test
      - name: Dump MySQL Error Log
        if: always()
        run: cat logs/mysql-error.log
      - name: Dump MySQL General Log
        if: always()
        run: cat logs/mysql-general.log
      - name: Kill
        if: always()
        run: make kill
